main:
  logging: WARN
history:
  file: data/history.csv
reference:
  file: data/reference.csv
feedback:
  file: data/download.csv
next_session:
  file: data/upload.csv
  max_records: 20
  max_period: 1.0
  new_record_period: 0.5